services:
    apache:
        image: tugboatqa/httpd
        aliases: test
        http: true
        https: false
        commands:
            init:
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            build:
                - cat .tugboat/tugboat.txt
        urls:
          - /
        visualdiff:
          threshold: 90
